Fix 3.1.0 upgrade
eXist-db/eXide pull request #335
Opened 2021-07-19 21:08 UTC by joewiz

Fixes issues introduced in the eXide 3.1.0 release by #328.

Closes #333 and #334.

2021-07-19 21:11 UTC, joewiz commented
@wolfgangmm Thanks for your help on today's Community Call! I tried integrating your suggestions—in https://github.com/eXist-db/eXide/pull/335/commits/ced6868a8291939f13966bf76094f0ac98429115. But, as my comment in preferences.js line 40 states, the addition of `eXide.app.version()` raised this error in the console:

> Uncaught TypeError: Cannot read property 'version' of undefined

This is strange, because the same expression can be found elsewhere in preferences.js. Do you have any suggestions for dynamically registering the version?

2021-10-14 16:51 UTC, joewiz commented
Note that once #374 is merged, the feature commit in #328 will need to be re-added to this branch so that work on the fix started here can proceed.

2021-11-09 17:05 UTC, wolfgangmm requested changes
See my inline comment.

2021-11-09 17:05 UTC, wolfgangmm commented on src/preferences.js
> +            this.preferences = Object.assign(defaultPreferences, JSON.parse(localStorage.getItem("eXide.preferences")));
This line should be changed as follows or the defaultPreferences would be overwritten:

```javascript
const loaded = JSON.parse(localStorage.getItem("eXide.preferences"));
this.preferences = Object.assign({}, defaultPreferences, loaded);
```

2021-11-09 17:06 UTC, wolfgangmm commented on src/preferences.js
> +            this.preferences = Object.assign(defaultPreferences, JSON.parse(localStorage.getItem("eXide.preferences")));
I tested above change on my local eXide install and it works as expected.

2021-11-16 09:04 UTC, wolfgangmm commented on index.html.tmpl
> +                                    <input type="checkbox" name="indent-on-load" id="indent-on-open"/>
Above needs to be changed to `name="indent-on-open"` for the setting to be picked up correctly.

2021-11-16 09:06 UTC, wolfgangmm commented on src/preferences.js
>          this.preferences.version = eXide.app.version();
Add `this.updateForm();` after `this.applyPreferences();` for the UI form to be updated.

2021-11-20 15:43 UTC, joewiz commented on index.html.tmpl
> +                                    <input type="checkbox" name="indent-on-load" id="indent-on-open"/>
@wolfgangmm Ugh, thank you for catching this! I thought I'd caught them all.

2021-11-20 15:43 UTC, joewiz commented on src/preferences.js
>          this.preferences.version = eXide.app.version();
@wolfgangmm `this.applyPreferences();` appears twice in preferences.js: first in `Constr.prototype.updatePreferences` (line 145) and second in `Constr.prototype.read` (line 195). Should I apply your suggested changes to both instances?

2021-11-21 16:29 UTC, wolfgangmm commented on src/preferences.js
>          this.preferences.version = eXide.app.version();
@joewiz it should only be applied to `Constr.prototype.read`.

2021-11-21 21:14 UTC, joewiz commented on index.html.tmpl
> +                                    <input type="checkbox" name="indent-on-load" id="indent-on-open"/>
Fixed in latest force-pushed commits.

2021-11-21 21:34 UTC, joewiz commented on src/preferences.js
>          this.preferences.version = eXide.app.version();
@wolfgangmm Thank you! I've applied this change to the latest force-pushed commits. It works perfectly in my testing. Prefs are picked up without a shift-reload; a simple reload when uploading does the trick.

2021-11-23 18:16 UTC, wolfgangmm approved these changes

2021-11-23 18:16 UTC, merged

2021-11-23 21:39 UTC, joewiz commented
@wolfgangmm Many thanks!