Switch resource handling from name to key
eXist-db/eXide pull request #489
Opened 2022-06-22 17:05 UTC by marmoure

Fixes #185 
this PR switches to using key for resources in the DB manager for copying,renaming,navigation,creation 
now creating a collection named `AéB` or with spaces in the name will work fine
![image](https://user-images.githubusercontent.com/30597211/175096333-97962966-acd0-4848-9983-fd4fa32cf338.png)

This open source contribution to the [eXide](https://github.com/eXist-db/eXide) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.

2022-06-23 22:06 UTC, joewiz commented
@marmoure I confirmed that creating, deleting, copying/pasting, and cutting/pasting collections works, but I encountered errors with accessing created collections; renaming collections; and renaming, copying/pasting, and cutting/pasting resources. I found some solutions but others will need your help. 

To reproduce the error accessing created collections:

1. Create `/db/AéB` with `xmldb:create-collection("/db", "AéB")`
2. In eXide's left sidebar in the "directory" tab, close and reopen the root `/db` collection. Notice that the "AéB" collection is shown.
3. In the same tab, open the `/db/AéB` subcollection. The operation silently fails. The Developer Tools > Network pane shows that the resulting call to the `collections.xq` http://localhost:8080/exist/apps/eXide/modules/collections.xq?root=/db/A%C3%A9B&view=r returns the following response:

    ```json
    { "status" : "fail", "#text" : "Collection /db/AéB not found. Could not locate collection: /db/AéB" }
    ```

A fix for this is to add `encodeURIComponent` around the `(sel.datum().key || "/db")` in https://github.com/eXist-db/eXide/blob/develop/src/directory.js#L79. 

To reproduce the error I observed renaming collections:

1. Using "File > Manage," select the "AéB" collection (created above), and select the "Rename" icon. 
5. In the now-editable resource name field, add a "2" to the collection name, and hit the "Return" key.
6. This raises an error dialog, titled "Rename Error":

> <img width="651" alt="Screen Shot 2022-06-23 at 3 44 30 PM" src="https://user-images.githubusercontent.com/59118/175387306-a007b691-69c8-4d44-a2c2-fd425302f8ac.png">

To reproduce the same issue with renaming resources, save the above query as `AéB.xq`, and repeat steps 2-4.

> <img width="650" alt="Screen Shot 2022-06-23 at 4 05 05 PM" src="https://user-images.githubusercontent.com/59118/175387609-3d077586-d736-44d4-90b0-53fabfe7ecc7.png">

To reproduce the same issue with copying/pasting and cutting/pasting, use "File > Manage" to copy the `AéB.xq` query into the `/db/AéB` collection. The operation appears to succeed, but when toggling the `/db/AéB` collection closed and open using eXide's left sidebar in the "directory" tab, the operation fails. (My suggested fix to directory.js above fixes this by encoding the "key.") 

Furthermore, when opening `/db/AéB/AéB.xq` in the editor pane, the path shown at the base of the editor pane is double-escaped: `/db/A%C3%A9B/A%C3%A9B.xq`. Here's a screenshot:

> <img width="754" alt="Screen Shot 2022-06-23 at 5 24 20 PM" src="https://user-images.githubusercontent.com/59118/175410329-1c29f535-bd54-432b-88c4-b197e88e2de7.png">

As a result, when clicking on the "arrow" icon to open the query in a new browser tab, the request returns a 404:

> <img width="602" alt="Screen Shot 2022-06-23 at 5 26 22 PM" src="https://user-images.githubusercontent.com/59118/175405207-0d1d64d4-5c2e-4bd6-8463-86ee9948ea55.png">

I think the code that sets the `href="/exist/rest/db/A%C3%A9B.xq"` and `<span class="path">/db/A%C3%A9B.xq</span>` shown in the screenshot above can be found at https://github.com/eXist-db/eXide/blob/develop/src/eXide.js#L961-L970. Unfortunately, since I don't know Javascript, I don't know how to further track down this problem.

2022-06-27 16:02 UTC, marmoure commented
hi @joewiz i fixed the breadcrumbs part but the issue with the page not found is an exist issue 
the rest client can't handle special characters in files name hopefully it will resolved soon
so this one can have a final test and get merged

2022-07-03 14:31 UTC, joewiz commented on cypress/integration/dbmanager.spec.js
> +            xmldb:store(xmldb:encode("/db/AéB"), xmldb:encode("AéB.xml"), <foo/>)`,
Is `xmldb:encode` correct here?

2022-07-03 14:50 UTC, marmoure commented on cypress/integration/dbmanager.spec.js
> +            xmldb:store(xmldb:encode("/db/AéB"), xmldb:encode("AéB.xml"), <foo/>)`,
yes seems like unlike xmldb: create which does the encoding on the backend store function doesn't

2022-07-03 14:52 UTC, marmoure commented
@joewiz  there seems to be some failures which came as surprise to me, i ll try to replicate the build process and see if I can reproduce them

2022-07-03 14:52 UTC, joewiz commented on cypress/integration/dbmanager.spec.js
> +            xmldb:store(xmldb:encode("/db/AéB"), xmldb:encode("AéB.xml"), <foo/>)`,
Very interesting, thanks! ... And definitely relevant to https://github.com/eXist-db/exist/issues/1824.

2022-07-03 16:18 UTC, marmoure commented
@joewiz yes i confirm `xmldb:store` does not encode either the file name nor the collection
![image](https://user-images.githubusercontent.com/30597211/177047952-8f21af8b-e1c8-4fd9-a062-e06aaaa8374a.png)
and `xmldb:create-collection` does encode the received collection name

2022-07-13 06:51 UTC, duncdrum requested changes, later dismissed
This PR is mixing concerns, and WIP. I see no reason for the changes to the ci config or for removing existing tests. Please make a separate PR for these so we can discuss them separately.

2022-07-13 09:12 UTC, marmoure commented
@duncdrum @joewiz this PR will be blocked till https://github.com/eXist-db/eXide/pull/498 is merged so we can have more details on the failures 
the tests are working fine when tested locally with the same steps as CI but somehow it's failing, i m suspecting the deployment phase.

2022-07-13 17:02 UTC, marmoure commented
According to this image 
![DB Manager -- DB Manager operations -- create resource -- should open resource (failed)](https://user-images.githubusercontent.com/30597211/178790055-12c9d1be-3701-4be7-a504-c13129275213.png)
The changes introduced in this PR are not deployed correctly 
@joewiz 
@duncdrum

2022-07-13 18:28 UTC, joewiz commented
I bet the stock version of eXide is being installed first before the version from this PR. We need a way either to prevent the stock version from being installed first or  to install our version over the stock one. Packages are present in eXist's autodeploy are installed during eXist's startup; they are installed in alphanumeric order, but before installing a package eXist first checks if a package of the same package URI is already installed, and if one has already installed, the package being checked is skipped. So if the stock version of eXide included in the eXist Docker image's autodeploy folder is eXide-2.0.0.xar, and the version that CI copies into the autodeploy folder is eXide-3.0.0.xar, then v2.0.0 will be installed and v3.0.0 will be skipped. I think this is the problem preventing our CI tests from testing the PR's version of eXide.

2022-07-13 23:17 UTC, marmoure commented
i ran a clean instance of the docker image and i checked the eXide version seems like it's "3.4.0"
@joewiz so the assumption exist isn't replacing exide because of old version it's not the case.

2022-07-13 23:22 UTC, marmoure commented
i tried deploying exist using a different method which was recommended by @adamretter but unfortunately it didn't work
the method was sending a POST request to rest client which uploads then deploy the `xar`
```sh
#!/bin/bash

EXIST_REST_URI="http://localhost:8080/exist/rest"
EXIST_REST_USERNAME="admin"
EXIST_REST_PASSWORD=""

function upload_pkg_files() {
	local pkg_file_name="eXide-$1.xar"
	local pkg_file="./build/eXide-$1.xar"
	
	local curl_cmd=(curl --fail --user "${EXIST_REST_USERNAME}:${EXIST_REST_PASSWORD}" -X PUT -H "Content-Type: application/octet-stream" --data-binary "@${pkg_file}" "${EXIST_REST_URI}/db/${pkg_file_name}")

	echo "Uploading ${pkg_file_name} to eXist-db..."
		"${curl_cmd[@]}"
	echo "Uploaded OK."
}

function deploy_pkg_files() {
	local deploy_xq="<query xmlns=\"http://exist.sourceforge.net/NS/exist\">
						<text>
							let \$pkg-name := \"http://exist-db.org/apps/eXide\"
							let \$pkg-final-name := \"eXide-$1\"
							return
							(
								repo:undeploy(\$pkg-name),
								repo:install-and-deploy-from-db(\"/db/\" || \$pkg-final-name || \".xar\")
							)
						</text>
					</query>"

	local curl_cmd=(curl --fail --user "${EXIST_REST_USERNAME}:${EXIST_REST_PASSWORD}" -X POST -H "Content-Type: application/xml" -d "${deploy_xq}" "${EXIST_REST_URI}/db/")

	echo "Deploying ${pkg_file_name} to eXist-db..."
	"${curl_cmd[@]}"
	echo ""
	echo "Deployed OK."

}

upload_pkg_files $1
deploy_pkg_files $1
```
this script was invoked in the CI with the current version number as arg

2022-07-15 05:21 UTC, marmoure commented
@joewiz after #500 is merged i ll rebase and run the tests again and hopefully it's a done deal

2022-07-15 05:35 UTC, joewiz commented
@marmoure #500 is merged.

2022-07-15 05:52 UTC, joewiz commented
@duncdrum Above you said:

> This PR is mixing concerns, and WIP. I see no reason for the changes to the ci config or for removing existing tests. Please make a separate PR for these so we can discuss them separately.

The CI changes were moved into a separate PR: #500. I merged that PR provisionally, as it enables work on this PR to proceed. Your comments are certainly still welcome. Are there test scenarios you believe should be retained? Perhaps we can look into restoring them. The CI changes in #500 were needed at the very least as a sanity check, since eXist wasn't installing the eXide packages built from PRs, and this would affect any new PRs with tests. So once the automated testing works again, if anything needs to be put back we can take a look into it.

2022-07-15 06:02 UTC, marmoure commented
@joewiz the deployment issue is no longer present but seems like we have some issues with the test runs it's flaky  
so far i haven't been able to  solve that as for the last run it was a login issue on one of the runs and that made everything fail

2022-07-15 06:46 UTC, marmoure commented
@joewiz after adding multiple wait statements to the tests  to slow down the runs it seems to be working as expected

2022-07-17 20:56 UTC, joewiz approved these changes
All tests pass locally and in CI.

2022-07-20 14:41 UTC, joewiz commented
@marmoure Thank you very much for this thorough and well-tested PR! This clears up an entire class of bugs that affected users of eXide who used special characters in resource names (including users of TEI Publisher - see https://github.com/eeditiones/tei-publisher-app/issues/48). We're on much more solid ground now, and the tests you added will flag any issues as we continue to investigate the related issues in the eXist core - https://github.com/eXist-db/exist/issues/1824 and https://github.com/eXist-db/exist/issues/3795.

2022-07-20 15:11 UTC, merged

2022-07-20 16:38 UTC, joewiz commented
p.s. A complementary CI fix was added to #503.